n_motors: 4                # [-]
mass: 2.0                  # [kg]
arm_length: 0.25           # [m]
body_height: 0.1           # [m]
motor_time_constant: 0.03  # [s]
g: 9.81                    # [ms^-2]
air_resistance_coeff: 0.25 # [-]

propulsion:

  # force [N] = force_constant * rpm^2
  force_constant: 0.00000022970

  # moment [Nm] = moment_constant * force [N]
  moment_constant: 0.07

  prop_radius: 0.15 # [m]

  # allocation motors -> moments

  # # quadrotor + configuration
  # allocation_matrix: [
  #   0,  0, 1,  -1,
  #   -1, 1, 0,  0,
  #   1,  1, -1, -1,
  #   1,  1, 1,  1,
  # ]

  # quadrotor X configuration
  allocation_matrix: [
    -0.707, 0.707, 0.707,  -0.707,
    -0.707, 0.707, -0.707, 0.707,
    -1,     -1,    1,      1,
    1,      1,     1,      1,
  ]

rpm:
  min: 895  # [revolutions/minute]
  max: 8951 # [revolutions/minute]
