hw_interface_plugin: "mrs_simulator_api_plugin/Api"

topics:
  simulator:
    imu: "multirotor_simulator/imu"
    odom: "multirotor_simulator/odom"
    attitude_rate_cmd: "multirotor_simulator/attitude_rate_cmd"
    attitude_cmd: "multirotor_simulator/attitude_cmd"
