hw_interface_plugin: "mrs_simulator_api_plugin/Api"

input_mode:
  actuators: false
  control_group: false
  attitude_rate: true
  attitude: true
  acceleration: true
  velocity: true
  position: false

topics:
  simulator:
    imu: "multirotor_simulator/imu"
    odom: "multirotor_simulator/odom"
    diagnostics: "multirotor_simulator/diagnostics"
    attitude_rate_cmd: "multirotor_simulator/attitude_rate_cmd"
    attitude_cmd: "multirotor_simulator/attitude_cmd"
    acceleration_cmd: "multirotor_simulator/acceleration_cmd"
    velocity_cmd: "multirotor_simulator/velocity_cmd"
