hw_interface_plugin: "mrs_simulator_api_plugin/Api"

input_mode:
  actuators: false
  control_group: false
  attitude_rate: true
  attitude: true
  acceleration: true
  velocity: true
  position: true

topics:
  prefix: "multirotor_simulator"
  simulator:
    # subscribers
    imu: "imu"
    odom: "odom"
    rangefinder: "rangefinder"
    # publishers
    attitude_rate_cmd: "attitude_rate_cmd"
    attitude_cmd: "attitude_cmd"
    acceleration_cmd: "acceleration_cmd"
    velocity_cmd: "velocity_cmd"
    position_cmd: "position_cmd"
