simulation_rate: 100.0 # Hz
realtime_factor: 1.0 # [-]

# ACTUATOR_CMD=0
# CONTROL_GROUP_CMD=1
# ATTITUDE_RATE_CMD=2
# ATTITUDE_CMD=3
# ACCELERATION_CMD=4
# VELOCITY_CMD=5
# POSITION_CMD=6
input_mode: 2
