simulation_rate: 100.0 # Hz
realtime_factor: 1.0 # [-]

g: 9.81 # [ms^-2]

iterate_without_input: true

input_timeout: 0.25 # [s]

frames:
  world:
    name: "simulator_origin"
    prefix_with_uav_name: false
  fcu:
    name: "fcu"
    publish_tf: true
  rangefinder:
    name: "garmin"
    publish_tf: true

collisions:
  enabled: true
  crash: false

  # if crash==false, then the collisions are elastic
  rebounce: 100.0

ground:
  enabled: true
  z: 0.0 # [m]

# * when enabled, this will place a temporary patch of ground just under the spawn location
# * this patch will disappear after the total_thrust > 0.9*hover_thrust
takeoff_patch:
  enabled: true
